version: '3.0'
services:
  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_ROOT_PASSWORD=leetcode
    ports:
    - "6603:3306"
    volumes:
    - ~/Documents/leetcode/:/docker-entrypoint-initdb.d
